johnny/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('johnny.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

johnny/models.py
from django.db import models
from django.db.models.base import Model
from django.core.validators import RegexValidator

# HOME SECTION


class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=5)
    greetings_2 = models.CharField(max_length=5)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                              on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)


# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)


# PORTFOLIO SECTION

class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'Portfolio {self.id}'


class Contact(models.Model):
    email = models.EmailField()
    phone_number_regex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone_number = models.CharField(
        validators=[phone_number_regex], max_length=16, unique=True)
    address = models.CharField(max_length=250)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Address'

johnny/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponse
from .models import Home, About, Portfolio, Category, Skills, Profile, Contact


def index(request):
    if(request.method == 'POST'):
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        message = request.POST.get('message')
        data = {
            'name': name,
            'subject': subject,
            'email': email,
            'message': message,
        }
        email_body = f'''
        New Messaage: {data['message']}

        From: {data['email']}
        '''.format(data['message'], data['email'])

        send_mail(data['subject'], email_body, '',
                  ['km.monzurul.islam@gmail.com'])
        return HttpResponse('Thanks for contacting me. I will be in touch soon.')
    # Home Record
    home = Home.objects.latest('updated')
    # About Record
    about = About.objects.latest('updated')
    # Portfolio
    profiles = Profile.objects.filter(about=about)
    facebook_link = profiles[0]
    linkedin_link = profiles[1]
    github_link = profiles[2]
    # Skills
    catagories = Category.objects.all()
    # Portfolios
    portfolios = Portfolio.objects.all()
    # My Contact
    contact = Contact.objects.latest('updated')

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'catagories': catagories,
        'portfolios': portfolios,
        'facebook_link': facebook_link,
        'linkedin_link': linkedin_link,
        'github_link': github_link,
        'contact': contact,
    }
    return render(request, 'html/index.html', context)

johnny/templates/html/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- ===== CSS ===== -->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}" />

    <!-- ===== BOX ICONS ===== -->
    <link
      href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css"
      rel="stylesheet"
    />

    <title>Johnny's Portfolio</title>
  </head>
  <body>
    <!--===== HEADER =====-->
    <header class="l-header">
      <nav class="nav bd-grid">
        <div>
          <a href="#" class="nav__logo">{{ home.name }}</a>
        </div>

        <div class="nav__menu" id="nav-menu">
          <ul class="nav__list">
            <li class="nav__item">
              <a href="#home" class="nav__link active">Home</a>
            </li>
            <li class="nav__item">
              <a href="#about" class="nav__link">About</a>
            </li>
            <li class="nav__item">
              <a href="#skills" class="nav__link">Skills</a>
            </li>
            <li class="nav__item">
              <a href="#portfolio" class="nav__link">Portfolio</a>
            </li>
            <li class="nav__item">
              <a href="#contact" class="nav__link">Contact</a>
            </li>
          </ul>
        </div>

        <div class="nav__toggle" id="nav-toggle">
          <i class="bx bx-menu"></i>
        </div>
      </nav>
    </header>

    <main class="l-main">
      <!--===== HOME =====-->
      <section class="home" id="home">
        <div class="home__container bd-grid">
          <h1 class="home__title">
            <span>{{ home.greetings_1 }}</span><br />{{ home.greetings_2 }}.
          </h1>

          <div class="home__scroll">
            <a href="#about" class="home__scroll-link"
              ><i class="bx bx-up-arrow-alt"></i>Scroll down</a
            >
          </div>

          <img src="{{ home.picture.url }}" alt="" class="home__img" />
        </div>
      </section>

      <!--===== ABOUT =====-->
      <section class="about section" id="about">
        <h2 class="section-title">About</h2>

        <div class="about__container bd-grid">
          <div class="about__img">
            <img src="{{ home.picture.url }}" alt="" />
          </div>

          <div>
            <h2 class="about__subtitle">{{ about.heading }}</h2>
            <span class="about__profession">{{ about.career }}</span>
            <p class="about__text">{{ about.description }}</p>
            <div class="about__social">
              <a
                href="{{ linkedin_link.link }}"
                class="about__social-icon"
                target="_blank"
                ><i class="bx bxl-linkedin"></i
              ></a>
              <a
                href="{{ facebook_link.link }}"
                class="about__social-icon"
                target="_blank"
                ><i class="bx bxl-facebook-circle"></i
              ></a>
              <a
                href="{{ github_link.link }}"
                class="about__social-icon"
                target="_blank"
                ><i class="bx bxl-github"></i
              ></a>
              <a href="#" class="about__social-icon"
                ><i class="bx bxl-dribbble"></i
              ></a>
            </div>
          </div>
        </div>
      </section>

      <!--===== SKILLS =====-->
      <section class="skills section" id="skills">
        <h2 class="section-title">Skills</h2>

        <div class="skills__container bd-grid">
          <div class="skills__box">
            {% for category in catagories %}
            <h3 class="skills__subtitle">{{ category.name }}</h3>
            {% for skills in category.skills_set.all %}

            <span class="skills__name">{{ skills.skill_name }}</span>
            {% endfor %} {% endfor %}
          </div>

          <div class="skills__img">
            <img src="{% static 'assets/img/skill.jpg' %}" alt="" />
          </div>
        </div>
      </section>

      <!--===== PORTFOLIO =====-->
      <section class="portfolio section" id="portfolio">
        <h2 class="section-title">Portfolio</h2>

        <div class="portfolio__container bd-grid">
          {% for portfolio in portfolios %}

          <div class="portfolio__img">
            <img src="{{ portfolio.image.url }}" alt="" />

            <div class="portfolio__link">
              <a href="{{ portfolio.link }}" class="portfolio__link-name"
                >View details</a
              >
            </div>
          </div>

          {% endfor %}
        </div>
      </section>

      <!--===== CONTACT =====-->
      <section class="contact section" id="contact">
        <h2 class="section-title">Contact</h2>

        <div class="contact__container bd-grid">
          <div class="contact__info">
            <h3 class="contact__subtitle">EMAIL</h3>
            <span class="contact__text">{{ contact.email }}</span>

            <h3 class="contact__subtitle">PHONE</h3>
            <span class="contact__text">{{ contact.phone_number }}</span>

            <h3 class="contact__subtitle">ADDRESS</h3>
            <span class="contact__text">{{ contact.address }}</span>
          </div>

          <form action="" method="POST" class="contact__form">
            {% csrf_token %}
            <div class="contact__inputs">
              <input
                type="text"
                placeholder="Name"
                class="contact__input"
                name="name"
                required
              />
              <input
                type="mail"
                placeholder="Email"
                class="contact__input"
                name="email"
                required
              />
              <input
                type="text"
                placeholder="Subject"
                class="contact__input"
                name="subject"
                required
              />
            </div>

            <textarea
              required
              name="message"
              placeholder="Your message goes here"
              id=""
              cols="0"
              rows="10"
              class="contact__input"
            ></textarea>

            <input type="submit" value="Send Message" class="contact__button" />
          </form>
        </div>
      </section>
    </main>

    <!--===== FOOTER =====-->
    <footer class="footer section">
      <div class="footer__container bd-grid">
        <div class="footer__data">
          <h2 class="footer__title">{{ home.name }}</h2>
          <p class="footer__text">
            I'm {{ home.name }} and this is my personal website
          </p>
        </div>

        <div class="footer__data">
          <h2 class="footer__title">EXPLORE</h2>
          <ul>
            <li><a href="#home" class="footer__link">Home</a></li>
            <li><a href="#about" class="footer__link">About</a></li>
            <li><a href="#skills" class="footer__link">Skills</a></li>
            <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
            <li><a href="#Contact" class="footer__link">Contact</a></li>
          </ul>
        </div>

        <div class="footer__data">
          <h2 class="footer__title">FOLLOW</h2>
          <a href="{{ facebook_link.link }}" class="footer__social"
            ><i class="bx bxl-facebook"></i
          ></a>
          <a href="#" class="footer__social"
            ><i class="bx bxl-instagram"></i
          ></a>
          <a href="#" class="footer__social"><i class="bx bxl-twitter"></i></a>
        </div>
      </div>
    </footer>

    <!--===== SCROLL REVEAL =====-->
    <script src="https://unpkg.com/scrollreveal"></script>

    <!--===== MAIN JS =====-->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>